l_german:

 CUSTOM_DIFFICULTY_GROUP_NAME:0 "KI-Buffs"
 diff_strong_ai_generic:0 "Stärkere KI"
 custom_diff_strong_ger:0 "Deutschland stärken"
 custom_diff_strong_ita:0 "Italien stärken"
 custom_diff_strong_sov:0 "Russland stärken"
 custom_diff_strong_fra:0 "Frankreich stärken"
 custom_diff_strong_eng:0 "Stärkung des Vereinigten Königreichs"
 custom_diff_strong_usa:0 "Stärkung der USA"
 custom_diff_strong_jap:0 "Japan stärken"
 custom_diff_strong_chi:0 "China stärken"
 custom_diff_strong_rus:0 "Russland stärken"
